namespace Jameak.RequestAuthorization.Core.Tests.TestUtilities.BuilderTypesForAssemblyScanTests;

internal class BuilderInheritingFromUserProvidedGenericAbstract : GenericAbstractRequestBuilder<TestRequest>
{
}
